### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-qbf01#3]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by SoxFace** [comment]
# Issue

When adding a new item in `/editor` the `image_url` field is not mandatory. 

If a user uploads an item without an image it presents as a broken image link.

![Uploading Screen Shot 2022-09-25 at 12.08.58 pm.png…](example broken image)

# Solution

Load the `/frontend/public/placeholder.png` if an image is not uploaded correctly.

# Screenshot of Fix

<img width="749" alt="Screen Shot 2022-09-25 at 12 43 34 pm" src="https://user-images.githubusercontent.com/4454398/192126645-95dafb9f-fd86-4214-8c40-75add4458a3a.png">
